assembly-versioning-scheme: MajorMinorPatch
mode: ContinuousDelivery
tag-prefix: '[vV]'
continuous-delivery-fallback-tag: ci
branches:
  master:
    tag: 
    increment: Patch
    prevent-increment-of-merged-branch-version: true
  release:
    mode: ContinuousDeployment
    tag: beta
  feature:
    mode: ContinuousDeployment
    tag: dev
    increment: Inherit
  hotfix:
    tag: beta
  support:
    tag: 
    increment: Patch
    prevent-increment-of-merged-branch-version: true
  develop:
    mode: ContinuousDeployment
    tag: dev
    increment: Minor
    track-merge-target: true
  pull-request:
    regex: (merge|merge\-requests|pr)[/-]
    mode: ContinuousDeployment
    tag: dev
    increment: Inherit
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
